#!/usr/bin/env python

import argparse
from runner import dump_to_file, parse_from_file

def parse_args(args=None):
    parser = argparse.ArgumentParser(
        description='Convert FIT and TCX files'
    )
    parser.add_argument(
        '-i', '--input', type=str, required=True,
        help='File to read from.',
    )
    parser.add_argument(
        '-o', '--output', type=str, required=True,
        help='File to output to.',
    )

    return parser.parse_args(args)

def main():
    options = parse_args()

    input_activity = parse_from_file(options.input)
    dump_to_file(input_activity, options.output)

if __name__ == '__main__':
    main()
